apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - grafana-instance.yaml
  - datasources/tempo-datasource.yaml
  - datasources/loki-datasource.yaml
  - datasources/prometheus-ocp-token-secret.yaml
  - datasources/prometheus-datasource.yaml
