apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-ocp
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "22"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: prometheus-ocp-token
          key: token

  instanceSelector:
    matchLabels:
      dashboards: grafana

  datasource:
    name: Prometheus-OCP
    type: prometheus
    access: proxy
    url: https://thanos-querier.openshift-monitoring.svc:9091
    jsonData:
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer ${token}"
